### ISSUE TITLE
Unexpected behavior with ending symbols

### ISSUE THREAD

**Issue by mitya52** [google-research/deduplicate-text-datasets#15]
Hi again,

I found that count-occurrences have an unexpected behavior if you  want to count last symbols in sequence. Here are the examples:
- sequence "aaabbb", query "b": expect 3, but output is ```Number of times present: 2```
- another one is when sequence "aaabbb", query "bb": expected 2, but actual output is ```Number of times present: 0```

Can you fix this? Thanks!

**Comment by carlini** [comment]
Thanks for catching this. It should be good now with 0008e616acfb1cdee33d036cf426642050b9a74d, I had previously unintentionally ignored the last N bytes for a file of length for queries of length N. This was a bug in the old code (it should have only ignored the last N-1 bytes) but now as part of the fix for #14 I don't need any length cap.

**Comment by mitya52** [comment]
I think you forgot to fix same workaround upper in line 286. When I patched it, all started to work well.
