### ISSUE TITLE
Accessing the duplicates and their counts

### ISSUE THREAD

**Issue by yanaiela** [google-research/deduplicate-text-datasets#20]
Hey, thanks for releasing the code!

I'm a bit confused regarding how to use the dups_ and sizes_ files.
I would like to get a mapping between all duplicate strings and their corresponding number of appearances in the data.
From my understanding, this is what you get with the points in those files, but I don't understand how to read these.
Any explanation, would be helpful! (and code snippet / reference even better!)

Thanks

**Comment by carlini** [comment]
Did you follow the README example? I tried to explain what's going on there with some code that shows processing it. Maybe if you could say what specifically is most unclear so I know what to answer that would be easiest to explain.

**Comment by yanaiela** [comment]
I did.
I'm confused about the part describing the pointers and the format of the duplicate files.

**Comment by daphnei** [comment]
Hi Yanai, sorry for the delayed response; this has been a busy month.

We don't have a single function which outputs a mapping between all duplicate strings and their corresponding number of appearances in the data. 

However, we do have a script which allows you to query the suffix array for how often each query string occurs. This is `scripts/count_occurrences.py`. There is an example for how to run it in the README.

**Comment by yanaiela** [comment]
Isn't that what's stored in "/cache/dups_$DATASET_A-B" and "/cache/sizes_$DATASET_A-B"

I understand how to get the number for a single query, but I would like to get the top-K occurrences in a specific dataset.
From my understanding the "dups_$DATASET_A-B" file contains the pointers for these duplicates, and the "sizes_$DATASET_A-B" file contains the info on their counts.
Is this correct?
If so, I'm struggling with understanding the format of these files.

**Comment by carlini** [comment]
Let me try maybe a simpler example.

Create a file and call it "banana.txt" and put into it "this is a bananana" [sic]. Now run `cargo run make --data-file banana.txt`. This makes a suffix array. Now run `cargo run self-similar banana.txt --length-threshold 2 --cache-dir /tmp/cache --num-threads 1`.

We should now have two files: dups and sizes. Let's ignore sizes for now, and just look at dups. My file has the following data

`0f0d 0b05 0210 0e0c 0603`

Each of these are single bytes pointing into our banana file. We said the length threshold is 2 so we'll take slices of length 2. These pointers are:

```
00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f 10 11
 t  h  i  s  _  i  s  _  a  _  b  a  n  a  n  a  n  a
```

so therefore
```
0f -> "an"
0d -> "an"
0b -> "an"
05 -> "is"
02 -> "is"
10 -> "na"
0e -> "na"
0c -> "na"
06 -> "s_"
03 -> "s_"
```

So we can see we've found all the length two duplicates, in order. Now if you're willing to look at the file you can see how these clusters fall. What the sizes file tells you is how many examples are in each cluster, 3, 2, 3, and 2 in this case. Indeed, if we cat the sizes file I get

```
0302 0302
```

So if I want to know "which cluster has the most repeats?" then I want to argsort on the sizes file, and then pull those examples out of the dups file.

In this example the code has allocated 1 byte for each pointer because the file length is short. For longer files it will use more bytes. (It will use the smallest pointer size possible.)

Does this make sense?

**Comment by yanaiela** [comment]
Thanks for the detailed explanation!!
I think the thing I don't understand is much simpler than that.
What is the format of the files `dups_...` and `sizes_...`?
And how did you convert (in the README) from `00000000: daa4 ae05 8c7a 8505 c7a4 ae05 797a 8505  .....z......yz`
to `0x05aea4da `

**Comment by carlini** [comment]
These files are raw bytes; there is no file format. Just cat the contents.

**Comment by yanaiela** [comment]
cool, thanks!
Do you happen to have a pointer for reading these files?

**Comment by carlini** [comment]
I don't understand what you mean? `open("sizes_...", "rb").read()` should do the trick?

**Comment by yanaiela** [comment]
I meant on how to parse the files. It's not trivial, but I managed to do it eventually.

**Comment by carlini** [comment]
Is there something that we could put in the README that would explain whatever you had trouble with so others could do it easier?

**Comment by longxudou** [comment]
Based on @yanaiela's code, we've implemented a [script](https://github.com/sail-sg/sailcraft/blob/main/code/exact_dedup/scripts/count_topk_occurrences.py) to count the top-k duplicates along with their frequencies. Additionally, we've enhanced this functionality by dynamically calculating the pointer size based on the ratio of sizes between the raw data file and its suffix array.

A specific case study is detailed in this [link](https://github.com/sail-sg/sailcraft#case-studies), showcasing deduplicated spans occurring more than twice within [a 1,000-line cc100 file](https://github.com/sail-sg/sailcraft/blob/main/data/data_input/sample.jsonl).

We extend our gratitude to the authors of this repository, with special thanks to @carlini. Leveraging this tool, we've built a data cleaning and deduplication tool called [SailCraft](https://github.com/sail-sg/sailcraft). We invite you to give it a try!
